// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///
/// defined in this file are the default Firebase configuration values for each platform supported by this app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw69nTHBvUlOIlRLKY-5MJwdK-tt3l0Y4',
    appId: '1:198170023835:web:7db68c958aca6db4cb733e',
    messagingSenderId: '198170023835',
    projectId: 'attendance-system-ea0d1',
    authDomain: 'attendance-system-ea0d1.firebaseapp.com',
    storageBucket: 'attendance-system-ea0d1.firebasestorage.app',
    measurementId: 'G-BV3C16E1W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCybF34khwAofbDy9VGkbTyMVYCdMBzNKA',
    appId: '1:198170023835:android:3fe4aa635658a4e6cb733e',
    messagingSenderId: '198170023835',
    projectId: 'attendance-system-ea0d1',
    storageBucket: 'attendance-system-ea0d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdDHm_J7nIbEQ-3wAZOxHoPehikM980U',
    appId: '1:198170023835:ios:3423f889148b040bcb733e',
    messagingSenderId: '198170023835',
    projectId: 'attendance-system-ea0d1',
    storageBucket: 'attendance-system-ea0d1.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxdDHm_J7nIbEQ-3wAZOxHoPehikM980U',
    appId: '1:198170023835:ios:3423f889148b040bcb733e',
    messagingSenderId: '198170023835',
    projectId: 'attendance-system-ea0d1',
    storageBucket: 'attendance-system-ea0d1.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw69nTHBvUlOIlRLKY-5MJwdK-tt3l0Y4',
    appId: '1:198170023835:web:edf35d8ea7c6d682cb733e',
    messagingSenderId: '198170023835',
    projectId: 'attendance-system-ea0d1',
    authDomain: 'attendance-system-ea0d1.firebaseapp.com',
    storageBucket: 'attendance-system-ea0d1.firebasestorage.app',
    measurementId: 'G-R3P1NNWFJB',
  );
}
